### ISSUE TITLE
Time Slider - maps, layers & geosearch

### ISSUE THREAD

**Issue by timwaters** [leidenwarper/mapwarper#3]
Metadata provided in import CSV or by the user upon manual upload should contain a year (e.g. 1784)
This should be in number format, and the system should check to make sure it is.
Time slider should appear as in NYPL warper on both the map / layer lists and in the geosearch.

**Comment by timwaters** [comment]
If a map has been added and it's not given a year - the default should be the current year

**Comment by erfgoedleiden** [comment]
Our current format for dates is yyyy-mm-dd. For excemple 1860-01-01. Can that be imported as well (without alterations)?

**Comment by timwaters** [comment]
There's a few different date fields for a Map:
- issue year  (this is used for search / time slider)
- date depicted
- reprint date
- published date

For a Layer/Mosaic there's just:
- depicts year

As for types - 

Some are year integer, or string YYYY
Some are full date times YYYY-MM-DD Minutes Hour etc

We can add new ones, and change existing ones if we want.

**Comment by timwaters** [comment]
By default, the min and max of the sliders are calculated by the min and max of all the maps in the database. For example, if the oldest map is from 1762 and the newest one from 2016 the slider will go from  1762<------------>2016

(At the beginning with an empty database it defaults to 1600 <----> 2016)
